## Importando las librerias necesarias

In [102]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score


## Cargando los datos

In [103]:
data = pd.read_csv('Dataset Lab7 - Hoja 1.csv')
data.head()

Gastos en Marketing  Gastos en planilla  Gastos en Alquiler       Ciudad  \
0                   52                2320                 560    Nashville   
1                  110                2120                 790      Indiana   
2                  324                3145                1230  Los Angeles   
3                  233                2540                1020      Indiana   
4                  130                1829                 525     Oklahoma   

   Ingresos por venta de productos  Outcome  
0                             3225        0  
1                             2130        1  
2                             3540        1  
3                             3675        0  
4                             2130        1

In [104]:
data.tail()

Gastos en Marketing  Gastos en planilla  Gastos en Alquiler       Ciudad  \
25                  272                2840                 630     Oklahoma   
26                  314                3378                 548      Indiana   
27                  254                3160                 789  Los Angeles   
28                  156                3132                 680    Nashville   
29                  139                2739                 646   California   

    Ingresos por venta de productos  Outcome  
25                             3972        0  
26                             4454        0  
27                             2948        1  
28                             2872        1  
29                             3135        1

### Transformando los datos de ciudades en numeros

In [105]:
data['Ciudad'] = data['Ciudad'].map({'California': 1, 'Indiana':2, 
                                     'Nashville':3, 'Oklahoma':4, 
                                     'Los Angeles':5})

data.head()

Gastos en Marketing  Gastos en planilla  Gastos en Alquiler  Ciudad  \
0                   52                2320                 560       3   
1                  110                2120                 790       2   
2                  324                3145                1230       5   
3                  233                2540                1020       2   
4                  130                1829                 525       4   

   Ingresos por venta de productos  Outcome  
0                             3225        0  
1                             2130        1  
2                             3540        1  
3                             3675        0  
4                             2130        1

## Extrayendo las variables

In [106]:
x = data.iloc[:, 0:5]
x.head()

Gastos en Marketing  Gastos en planilla  Gastos en Alquiler  Ciudad  \
0                   52                2320                 560       3   
1                  110                2120                 790       2   
2                  324                3145                1230       5   
3                  233                2540                1020       2   
4                  130                1829                 525       4   

   Ingresos por venta de productos  
0                             3225  
1                             2130  
2                             3540  
3                             3675  
4                             2130

In [107]:
y = data.iloc[:, 5]
y.head()

0    0
1    1
2    1
3    0
4    1
Name: Outcome, dtype: int64

## Dividiendo la data en 2 => Training Data y Test Data

In [108]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

## Estandarizando los datos para poder usar la metrica de Euclidean

In [109]:
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

X_test

array([[ 0.9595869 ,  0.52088885,  4.72580191,  1.50117325,  0.15729465],
       [-0.82221446,  0.49856504,  0.20059779, -0.07505866, -0.71381841],
       [ 0.9595869 , -0.12821879,  1.07272804, -1.65129058,  1.03623208],
       [ 0.43989484,  0.22037605, -0.95127235, -1.65129058,  0.7206492 ],
       [ 0.8535273 ,  0.92100018, -0.88545119, -0.86317462,  1.34920683],
       [-0.7055489 , -0.18488692, -0.42470314, -0.07505866, -1.27717296],
       [ 0.21716967,  0.54664709,  1.09741097,  1.50117325, -0.61470973],
       [ 1.15049419, -0.3325675 , -1.00063821,  0.71305729,  0.42071507],
       [ 0.52474252,  0.8591804 , -0.35888199, -1.65129058, -1.4010588 ]])

## Calculando la cantidad de neighbors para el KNN

In [110]:
import math
math.sqrt(len(y_test))

3.0

## Definiendo el modelo KNN

In [111]:
classifier = KNeighborsClassifier(n_neighbors=3, p=2, metric='euclidean')


### Ajustando el modelo

In [112]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

### Prediciendo con el Test Data

In [113]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 1, 1, 0, 1])

## Evaluando el modelo

In [114]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[3, 1],
       [0, 5]])

In [115]:
f1_score(y_test, y_pred)

0.9090909090909091

In [116]:
accuracy_score(y_test, y_pred)

0.8888888888888888